export const CREATE_CONTACT_REQUEST = 'CREATE_CONTACT_REQUEST';
export const CREATE_CONTACT_SUCCESS = 'CREATE_CONTACT_SUCCESS';
export const CREATE_CONTACT_FAIL = 'CREATE_CONTACT_FAIL';
export const CREATE_CONTACT_RESET = 'CREATE_CONTACT_RESET';

export const ALL_CONTACTS_REQUEST = 'ALL_CONTACTS_REQUEST';
export const ALL_CONTACTS_SUCCESS = 'ALL_CONTACTS_SUCCESS';
export const ALL_CONTACTS_FAIL = 'ALL_CONTACTS_FAIL';

export const CONTACT_DETAIL_REQUEST = 'CONTACT_DETAIL_REQUEST';
export const CONTACT_DETAIL_SUCCESS = 'CONTACT_DETAIL_SUCCESS';
export const CONTACT_DETAIL_FAIL = 'CONTACT_DETAIL_FAIL';

export const UPDATE_CONTACT_REQUEST = 'UPDATE_CONTACT_REQUEST';
export const UPDATE_CONTACT_SUCCESS = 'UPDATE_CONTACT_SUCCESS';
export const UPDATE_CONTACT_RESET = 'UPDATE_CONTACT_RESET';
export const UPDATE_CONTACT_FAIL = 'UPDATE_CONTACT_FAIL';


export const DELETE_CONTACT_REQUEST = 'DELETE_CONTACT_REQUEST';
export const DELETE_CONTACT_SUCCESS = 'DELETE_CONTACT_SUCCESS';
export const DELETE_CONTACT_FAIL = 'DELETE_CONTACT_FAIL';
export const DELETE_CONTACT_RESET = 'DELETE_CONTACT_RESET';

export const CLEAR_ERROR = 'CLEAR_ERROR';